### ISSUE TITLE
[Bug] MINIMAL_MARKETCAP error

### ISSUE THREAD

**Issue by AdamB2023** [tsarbuig/WalletHunter#4]
```-- SWAP DETECTED -----------------------------------------------
01-31 00:08:14.814  Tx 0xc3268108a89aeafb9241912cca93d217b688186214c42e949c1464affd62a2a7 from #8: 0xcf289AD73A0ca09916aD10f2b9B6fC56e60F3EfE - id: a2a7

a2a7 -- PRE-CHECKS BEFORE Tx ----------------------------------------
01-31 00:08:14.814  a2a7 - TX GAS CONTROL ------- Tx GAS = 19.663946214 and current GAS price = 18.061984913  --> let's continue
01-31 00:08:14.814  a2a7 - MINIMAL_MARKETCAP ---- Error --> please report it to Tsarbuig
01-31 00:08:14.814  undefined
Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x53DC3A7021A5e0a5286ee66163C7CcbFB373Ca8C","to":"0x7a250d5630B4cF
539739dF2C5dAcb4c659F2488D","data":"0xd06ca61f0000000000000000000000000000000000000000000000000000000005f5e1000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000200000000000
0000000000000718a28c2e5bf6943424740d278111b20472ad52c000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2","accessList":null}, error={"code":-32000,"response":"{\"jsonrpc\":\"2.0\",\"id\":588043,\"error\":{\"code\":-32000,\"message\":\"e
xecution reverted\"}}\n"}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (/snapshot/WalletHunterJs/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/snapshot/WalletHunterJs/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at checkError (/snapshot/WalletHunterJs/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:108:16)
    at WebSocketProvider.<anonymous> (/snapshot/WalletHunterJs/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:751:47)
    at step (/snapshot/WalletHunterJs/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/snapshot/WalletHunterJs/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/snapshot/WalletHunterJs/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'missing revert data in call exception; Transaction reverted without a reason string',
  code: 'CALL_EXCEPTION',
  data: '0x',
  transaction: {
    from: '0x53DC3A7021A5e0a5286ee66163C7CcbFB373Ca8C',
    to: '0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D',
    data: '0xd06ca61f0000000000000000000000000000000000000000000000000000000005f5e10000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000718a28c2e5bf
6943424740d278111b20472ad52c000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
    accessList: null
  },
  error: Error: execution reverted
      at WebSocket.<anonymous> (/snapshot/WalletHunterJs/node_modules/@ethersproject/providers/lib/websocket-provider.js:133:33)
      at WebSocket.onMessage (/snapshot/WalletHunterJs/node_modules/ws/lib/event-target.js:132:16)
      at WebSocket.emit (node:events:527:28)
      at Receiver.receiverOnMessage (/snapshot/WalletHunterJs/node_modules/ws/lib/websocket.js:834:20)
      at Receiver.emit (node:events:527:28)
      at Receiver.dataMessage (/snapshot/WalletHunterJs/node_modules/ws/lib/receiver.js:437:14)
      at Receiver.getData (/snapshot/WalletHunterJs/node_modules/ws/lib/receiver.js:367:17)
      at Receiver.startLoop (/snapshot/WalletHunterJs/node_modules/ws/lib/receiver.js:143:22)
      at Receiver._write (/snapshot/WalletHunterJs/node_modules/ws/lib/receiver.js:78:10)
      at writeOrBuffer (node:internal/streams/writable:389:12) {
    code: -32000,
    response: '{"jsonrpc":"2.0","id":588043,"error":{"code":-32000,"message":"execution reverted"}}\n'
  },
  level: 'info',
  timestamp: '01-31 00:08:14.814',
  [Symbol(level)]: 'info',
  [Symbol(message)]: '01-31 00:08:14.814 missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"from":"0x53DC3A7021A5e0a5286ee66163C7Cc
bFB373Ca8C","to":"0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D","data":"0xd06ca61f0000000000000000000000000000000000000000000000000000000005f5e100000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000
00000000000000000000002000000000000000000000000718a28c2e5bf6943424740d278111b20472ad52c000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2","accessList":null}, error={"code":-32000,"response":"{\\"jsonrpc\\":\\"2.0\\",\\"id\\":588043,\\
"error\\":{\\"code\\":-32000,\\"message\\":\\"execution reverted\\"}}\\n"}, code=CALL_EXCEPTION, version=providers/5.7.2)'
}
01-31 00:08:14.814  a2a7 - AMOUNT CONTROL ------- WARNING : this must be a Sniping Tx, cannot calculate precisely BNB value --> let's use tx.value
01-31 00:08:14.814  a2a7 - AMOUNT CONTROL ------- MINIMUM_BUY_AMOUNT_IN_BASE (0.012) <= your buyAmount (0.075) <= MAXIMUM_BUY_AMOUNT_IN_BASE (0.1) --> let's buy
01-31 00:08:14.814  a2a7 - GAS CALCULATION ------ Tx GAS = 19.663946214 --> your Tx GAS = 110% * 19.663946214 = 21.630340835
```

**Comment by tsarbuig** [comment]
already solved in last versions
